### ISSUE TITLE
Update graphics

### ISSUE THREAD

**Issue by JochenTimmermans** [JochenTimmermans/hangman#1]
The hangman graphics could use a little update.

**Comment by VictorPascu** [comment]
Hello there! Saw this issue on Hacktoberfest and decided to take a shot at it (changes visible using Rich Diff on the PR):
https://github.com/JochenTimmermans/hangman/pull/3

Also wrote some steps to getting the project running locally:
https://github.com/JochenTimmermans/hangman/pull/2

Hope this helps.
